alias: 'Switch on the lamp 5 progressively (3a)'
trigger:
  platform: template
  value_template: '{{ now.time().strftime("%-H") == states.sensor.alarm_clock_hour.state and now.time().strftime("%-M") == states.sensor.alarm_clock_minute.state }}'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.alarm_clock_status
      state: 'on'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
action:
  # minute 0 to 1
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 45
      rgb_color: [255, 0, 0] # red
  - delay:
#      minutes: 1
      seconds: 5
 # minute 1 to 2
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 60
      rgb_color: [255, 51, 51] 
  - delay:
      seconds: 5
#      minutes: 1
  # minute 2 to 3
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 75
      rgb_color: [255, 102, 102] 
  - delay:
      seconds: 5
#      minutes: 1
  # minute 3 to 4
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 90
      rgb_color: [255, 128, 0]
  - delay:
      seconds: 5
#      minutes: 1
  # minute 4 to 5
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 105
      rgb_color: [255, 153, 51]
  - delay:
      seconds: 5
#      minutes: 1
  # minute 5 to 6
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 120
      rgb_color: [255, 178, 102]
  - delay:
      seconds: 5
#      minutes: 1
  # minute 6 to 7
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 135
      rgb_color: [255, 204, 153]
  - delay:
      seconds: 5
#      minutes: 1
  # minute 7 to 8
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 150
      rgb_color: [255, 229, 204]
  - delay:
      seconds: 5
#      minutes: 1
  # minute 8 to 9
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 165
      rgb_color: [255, 255, 204]
  - delay:
      seconds: 5
#      minutes: 1
  # minute 9 to 10
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 180
      rgb_color: [255, 255, 153]
  - delay:
      seconds: 5
#      minutes: 1
  # minute 10 to 11
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 195
      rgb_color: [255, 255, 102]
  - delay:
      seconds: 5
#      minutes: 1
  # minute 11 to 12
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 210
      rgb_color: [255, 255, 51]
  - delay:
      seconds: 5
#      minutes: 1
  # minute 12 to 13
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 225
      rgb_color: [255, 255, 0]
  - delay:
      seconds: 5
#      minutes: 1
  # minute 13 to 14
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 240
      rgb_color: [255, 255, 255]
  - delay:
      seconds: 5
#      minutes: 1
  # minute 14 to 15
  - service: light.turn_on
    data:
      entity_id: light.lamp_5
      brightness: 255
      rgb_color: [255, 255, 255]
  - delay:
      seconds: 5
#      minutes: 1
  - service: light.turn_on
    entity_id: light.lamp_6
  - service: light.turn_off
    entity_id: light.lamp_5
  # https://home-assistant.io/cookbook/notify_if_over_threshold/
  - service: notify.notify
    data_template:
      message: >
        Hi Sam ! It's time to wake up ! It's {{ states.sensor.forecastio_temperature.state | round(0) }} degrees Celcius outside and the maximum temperature will be {{ states.sensor.forecastio_daily_high_temperature.state | round(0) }}. There's a {{ states.sensor.forecastio_precip_probability.state | round(0) }}% chance of rain today.
        {% if states('sensor.forecastio_precip_probability') | int > 50 %}
        Don't forget to bring your favorite umbrella! Have a nice (and rainy) day !
        {% else %}
        Have a nice day!
        {% endif %}
