alias: 'Switch on the lamp 1, 2, 5 & 6 on arrival of an inhabitantn (1d)'
trigger:
  platform: state
  entity_id: device_tracker.samuel_phone
  from: 'not_home'  
  to: 'home'
condition:
  condition: and
  conditions:
    - condition: time
      after: '22:30:00'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
action:
  - service: light.turn_on
    entity_id:
      - light.lamp_1
      - light.lamp_2
      - light.lamp_5
      - light.lamp_6
  - delay:
      minutes: 3
  - service: light.turn_off
    entity_id:
      - light.lamp_1
      - light.lamp_2
